Progress towards possibility of variable-sized segments
cs240-illinois/sp22_cs240_infinite-maze-shared pull request #7
Opened 2022-04-26 20:47 UTC by jasyip

Idea is that to support variable-sized segments, one big problem is to analyze the map for the space available in front of the player. This PR will try to solve it with a pure function that will calculate possible dimensions for potential segments based on given data. This means, the JavaScript will also need to be modified to provide more data. I have only wrote detailed documentation of this function as of now, more commits of actual code will come soon.

2022-04-26 21:44 UTC, pcrain commented
Looks good so far! 😃 Will look over again and hopefully merge once you've finished the implementation.

2022-04-30 20:47 UTC, wadefagen requested changes
Noticed some merge markers in a quick glance at this code

2022-04-30 20:47 UTC, wadefagen commented on .gitignore
> +<<<<<<< HEAD
This has git merge markers in the file itself -- please fix these

2022-05-01 03:02 UTC, jasyip commented
Main function is finished. I can try to analyze and modify the middleware/frontend a bit to send more data and modify which MGs are chosen, but may take a few days without help from other people on this issue.

2022-05-01 03:37 UTC, jasyip commented
Modifications needed for middleware:

- requests to middleware's `/generateSegment` should include the direction the player intended to move in.
- the data structure storing the global segment stores each individual coordinate as keys. I would have to convert it to a collection of square boundaries, wasting computational resources, so why not store the square boundaries *as* the keys?
- MGs will have to incorporate more data, such as the offsets of all of their exits on each side, hopefully it's not too much of a drastic change
- may have to make the random MG chooser more complex?

2022-05-01 18:18 UTC, wadefagen commented
> Edit: I also fixed my .gitignore having a merge artificat but I don't know how to get the Changes Requested notification to go away

On the reviewer area, you should be able to press the "refresh" button next to the name of the person who requested the change:
![image](https://user-images.githubusercontent.com/7505610/166159089-587bdc62-a740-44b4-a7de-38322e03e5d1.png)

2022-05-01 18:28 UTC, jasyip commented
> > Edit: I also fixed my .gitignore having a merge artificat but I don't know how to get the Changes Requested notification to go away
> 
> On the reviewer area, you should be able to press the "refresh" button next to the name of the person who requested the change: ![image](https://user-images.githubusercontent.com/7505610/166159089-587bdc62-a740-44b4-a7de-38322e03e5d1.png)

Done.

I'm going to try to spend some time figuring out how to modify some stuff in the middleware right now.

2022-05-01 20:40 UTC, jasyip commented
I changed `app.py` `generateSegment` to make use of the function, but a lot of the middleware needs to have a different structure. I may not be able to finish this by today, but other people can help out.

2022-05-05 17:14 UTC, pcrain commented
@jasyip I think some of the other students were able to incorporate the ideas and functionality you started into the shared middleware. I don't know if your commits will show up in the history but we'll make sure you get credit either way. Thank you very much for all of your hard work on the variable-sized segments! :smile:

2022-05-05 17:14 UTC, closed without merging